### PR TITLE
Hard fp and disable harfbuzz

### PR DESCRIPTION
**Pull request by xerpi**

### CODE REVIEW

**Comment by mtheall** [comment]
What is the purpose of disabling harfbuzz?

**Comment by xerpi** [comment]
Freetype can optionally use another lib to help with font rendering, called Harfbuzz. By default it was enabled so freetype gave me a few undefined references when building my app. I tried to compile Harfbuzz but didn't succeed, maybe I/we should try this approach or we just disable Harfbuzz.

**Comment by mtheall** [comment]
I have used freetype as-is here without disabling harfbuzz. Perhaps you were using different APIs which have a dependency there. I would prefer to try adding the harfbuzz library here; maybe you can show me some code that you're trying to compile which has the link errors you describe and I can try to get it working.

**Comment by xerpi** [comment]
I was trying to build my sf2dlib sample, which was building nice before formatting my PC yesterday: https://github.com/xerpi/sf2dlib

**Comment by Cruel** [comment]
I had to disable harfbuzz too. You should either add it to the portlibs or disable it, it's broken otherwise.

Here are the errors from the linker if you're curious: http://ix.io/iSj (all seem to be from autofit.c)

It's just drawing blue blocks atm, but I'm confident that it's because I'm doing some things wrong lol. My shader/GPU stuff is in a terrible state while I'm debugging stuff. Did this happen to you, @xerpi ?

**Comment by WinterMute** [comment]
These problems appear to have been dealt with in other commits

**Pull request closed without merging**
